version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "ilya40umov"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "monthly"
    reviewers:
      - "ilya40umov"
