management:
  tracing:
    enabled: true
    baggage:
      correlation:
        fields: country, userId
      # XXX local-fields are not supported in Spring Boot 3.x yet
      # see BraveAutoConfiguration
      # https://stackoverflow.com/questions/76635378/local-fields-missing-in-micrometer-tracing-as-compared-to-sleuth
      remote-fields: country, userId
    sampling:
      probability: 1.0