management:
  tracing:
    enabled: true
    baggage:
      correlation:
        fields: country, userId
      remote-fields: country, userId
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans

spring:
  application:
    name: 06-service-b

server:
  port : 8081