{
 "title": "01-logback-mdc",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Log Records By Country",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"01-logback-mdc\"}[1m])) by (country)"
    }
   ]
  },
  {
   "title": "Log Records By Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(count_over_time({app=\"01-logback-mdc\"}[1m])) by (level)"
    }
   ]
  },
  {
   "title": "Logs",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "{app=\"01-logback-mdc\"}"
    }
   ]
  }
 ]
}