management:
  tracing:
    enabled: true
    baggage:
      correlation:
        fields: country, userId
      remote-fields: country, userId
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  otlp:
    tracing:
      endpoint: http://localhost:4318/v1/traces

spring:
  application:
    name: 06-service-a